version: 2
updates:
  - package-ecosystem: maven
    directory: "/contact-microservice"
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: "/opportunity-microservice"
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: "/interaction-microservice"
    schedule:
      interval: daily

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"