apiVersion: v1
kind: ConfigMap
metadata:
   name: contact-db-config
data:
 host: contact-db-service

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: contact-db
  name: contact-db-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30020
  selector:
    app: contact-db
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: contact-db
  labels:
    app: contact-db
spec:
  serviceName: contact-db-service
  replicas: 1
  selector:
    matchLabels:
      app: contact-db
  template:
    metadata:
      labels:
        app: contact-db
        name: contact-db-service
    spec:
      containers:
        - name: contact-db
          image: mongo:latest
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.25"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: contact-db-pvc
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: contact-db-pvc
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi