apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: contact-service
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: contact-service
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: interaction-service
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: interaction-service
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: opportunity-service
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: opportunity-service
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80