kind: Service
apiVersion: v1
metadata:
  name: interaction-service
spec:
  selector:
    app: interaction-service
  ports:
  - protocol: TCP
    port: 8081
    nodePort: 30011
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
spec:
  selector:
      matchLabels:
        app: interaction-service
  replicas: 1
  template:
    metadata:
      labels:
        app: interaction-service
    spec:
      containers:
        - name: interaction-service
          image: 10.110.56.71:5000/interaction-microservice:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: interaction-db-config  
                  key: host
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.25"