apiVersion: v1
kind: ConfigMap
metadata:
   name: interaction-db-config
data:
 host: interaction-db-service

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: interaction-db
  name: interaction-db-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30021
  selector:
    app: interaction-db
  type: NodePort
    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: interaction-db
  labels:
    app: interaction-db
spec:
  serviceName: interaction-db-service
  replicas: 1
  selector:
    matchLabels:
      app: interaction-db
  template:
    metadata:
      labels:
        app: interaction-db
        name: interaction-db-service
    spec:
      containers:
        - name: interaction-db
          image: mongo:latest
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.25"
          ports:
            - containerPort: 27017
              name: interaction-db
          volumeMounts:
            - name: interaction-db-pvc
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: interaction-db-pvc
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi