name: CRM Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.3]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.0.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./crm-frontend/package-lock.json
    - run: npm ci
      working-directory: ./crm-frontend
    - run: npm run build --if-present
      working-directory: ./crm-frontend
    - run: npm test
      working-directory: ./crm-frontend
