name: Opportunity Microservice CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Set up MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
    - name: Build opportunity microservice with Maven
      working-directory: ./opportunity-microservice
      run: mvn -B package --file pom.xml
